name: Docker Compose Action
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: isbang/compose-action@v1.5.1
      with:
        compose-file: "./compose.yaml"
        up-flags: "--build --no-start"
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        cd ./backend
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
    - name: Install playwright and browsers
      run: |
        pip install playwright
        playwright install | playwright install-deps
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov pytest-playwright
        pytest ./backend --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
